language: node_js

node_js:
  - "5"
  - "6"
  - "7"
  - "stable"

sudo: false

cache:
  yarn: true

script:
  - npm run lint
  - npm run build
  # TODO: add testing with KarmaJS
  # TODO: add depcheck testing (with KarmaJS?)
