runtime: nodejs
api_version: 1
threadsafe: true

handlers:
- url: /assets/(.*)
  static_files: dist/assets/\1
  upload: dist/assets/(.*)
  secure: always

- url: /.*
  static_files: dist/index.html
  upload: dist/index.html
  secure: always
