export const FILTER = 'FILTER';

export const SUBSCRIBE      = 'SUBSCRIBE';
export const SUBSCRIBE_USER = 'SUBSCRIBE_USER';

export const VALIDATE_EMAIL    = 'VALIDATE_EMAIL';
export const VALIDATE_PASSWORD = 'VALIDATE_PASSWORD';

export const REGISTER_LOCAL_USER    = 'REGISTER_LOCAL_USER';
export const ADD_LOCAL_USER_SUCCESS = 'ADD_LOCAL_USER_SUCCESS';
export const ADD_LOCAL_USER_FAILED  = 'ADD_LOCAL_USER_FAILED';
export const LOCAL_REGISTER_CLICK   = 'LOCAL_REGISTER_CLICK';
