export const FILTER = 'FILTER';

export const SUBSCRIBE = 'SUBSCRIBE';
export const SUBSCRIBE_USER = 'SUBSCRIBE_USER';

// INTERESTS PAGE ACTIONS
export const CLICK_INTEREST_BOX = 'TOGGLE_INTEREST_BOX';
