export default {
    SplashPage: ['HTML', 'CSS', 'JavaScript', 'Hosting'],
    MultiplePageStaticWebsite: ['HTML', 'CSS', 'JavaScript', 'Hosting'],
    WebsiteWithABlog: ['HTML', 'CSS', 'JavaScript', 'Backend', 'Databases', 'CMS'],
    WebsiteWithMultipleContentSources: ['HTML', 'CSS', 'JavaScript', 'Backend', 'Databases', 'CMS'],
    UserAccountWebsite: ['HTML', 'CSS', 'JavaScript', 'Backend', 'Databases', 'CMS'],
    ECommerceWebsite: ['HTML', 'CSS', 'JavaScript', 'Backend', 'Databases', 'CMS', 'E-Commerce'],
    SmallIOSApplication: ['iOS', 'Xcode', 'Swift'],
    SmallAndroidApplication: ['Android', 'App Studio', 'Java'],
    MediumIOSApplication: ['Swift', 'iOS', 'React Native', 'XCode'],
    MediumAndroidApplication: ['Swift', 'iOS', 'React Native', 'XCode'],
    LargeIOSApplication: ['Swift', 'iOS', 'React Native', 'XCode'],
    LargeAndroidApplication: ['Swift', 'iOS', 'React Native', 'XCode'],
    Issue: [],
    SetupAdvice: [],
    DomainNameSetup: ['DNS', 'Hosting'],
    HostingSetup: ['DNS', 'Hosting'],
    DomainAndHostingSetup: ['DNS', 'Hosting'],
    DataBackup: ['Data', 'Databases', 'Hosting'],
    WebsiteTransfer: ['DNS', 'Hosting', 'Database'],
    MediumCloudArchitecture: ['Cloud Services', 'Software Architecture', 'Databases', 'Deployment', 'DNS', 'Hosting'],
    LargeCloudArchitecture: ['Cloud Services', 'Software Architecture', 'Databases', 'Deployment', 'DNS', 'Hosting'],
    APIDevelopment: ['Backend', 'Database'],
    SmallDevelopmentFeature: ['Backend', 'Database'],
    MediumDevelopmentFeature: ['Backend', 'Database'],
    LargeDevelopmentFeature: ['Backend', 'Database'],
    ExcelDataAnalysis: ['Data Analytics', 'Excel'],
    SQLQueryAnalysis: ['Data Analytics', 'SQL', 'Database'],
    SimpleDataVisualization: ['Data Analytics', 'Data Visualization', 'Backend', 'SQL', 'Excel'],
    AdvancedDataVisualization: ['Data Analytics', 'Data Visualization', 'Backend', 'SQL', 'Excel'],
    ComplexDataAnalysis: ['Data Analytics', 'Backend', 'Python', 'R'],
    SimpleMachineLearning: ['Data Analytics', 'Machine Learning', 'Python', 'R', 'Backend'],
    IntermediateMachineLearning: ['Data Analytics', 'Machine Learning', 'Python', 'R', 'Backend'],
    ComplexMachineLearning: ['Data Analytics', 'Machine Learning', 'Python', 'R', 'Backend'],
    LogoDesign: ['Branding', 'Graphic Design', 'Adobe'],
    Typography: ['Branding', 'Graphic Design', 'Typography'],
    ColorScheme: ['Branding', 'Graphic Design'],
    BrandConsulting: ['Branding', 'Graphic Design'],
    FullRebrand: ['Branding', 'Graphic Design', 'Typography', 'Adobe'],
    NewBranding: ['Branding', 'Graphic Design', 'Typography', 'Adobe'],
    UIConsulting: ['UI/UX', 'Branding'],
    FullSitePrototype: ['UI/UX', 'Branding', 'Prototyping'],
    FullAppPrototype: ['UI/UX', 'Branding', 'Prototyping'],
    FullProductPrototype: ['UI/UX', 'Branding', 'Prototyping'],
    SocialMediaConsulting: ['Social Media', 'Branding'],
    SocialMediaSetup: ['Social Media', 'Branding'],
    SocialMediaCampaign: ['Social Media', 'Branding'],
    AdvertisementConsulting: ['Advertisement', 'Consulting'],
    DigitalAdvertisement: ['Advertisement', 'Graphic Design'],
    PrintAdvertisement: ['Advertisement', 'Graphic Design'],
    VideoAdvertisement: ['Advertisement', 'Video Production', 'Video Editing'],
    FullAdvertisementCampaign: ['Advertisement', 'Graphic Design']
};
