export default {
    SplashPage: ['HTML', 'CSS', 'JavaScript', 'Hosting'],
    MultiplePageStaticWebsite: ['HTML', 'CSS', 'JavaScript', 'Hosting'],
    WebsiteWithABlog: ['HTML', 'CSS', 'JavaScript', 'Backend', 'Databases', 'CMS'],
    WebsiteWithMultipleContentSources: ['HTML', 'CSS', 'JavaScript', 'Backend', 'Databases', 'CMS'],
    UserAccountWebsite: ['HTML', 'CSS', 'JavaScript', 'Backend', 'Databases', 'CMS'],
    ECommerceWebsite: ['HTML', 'CSS', 'JavaScript', 'Backend', 'Databases', 'CMS', 'E-Commerce'],
    SmallIOSApplication: ['iOS', 'Xcode', 'Swift'],
    SmallAndroidApplication: ['Android', 'App Studio', 'Java'],
    Issue: [],
    SetupAdvice: [],
    DomainNameSetup: ['DNS', 'Hosting'],
    HostingSetup: ['DNS', 'Hosting'],
    DomainAndHostingSetup: ['DNS', 'Hosting'],
    DataBackup: ['Data', 'Databases', 'Hosting'],
    WebsiteTransfer: ['DNS', 'Hosting', 'Database'],
    MediumCloudArchitecture: ['Cloud Services', 'Software Architecture', 'Databases', 'Deployment', 'DNS', 'Hosting'],
    LargeCloudArchitecture: ['Cloud Services', 'Software Architecture', 'Databases', 'Deployment', 'DNS', 'Hosting'],
    APIDevelopment: ['Backend', 'Database'],
    SmallDevelopmentFeature: ['Backend', 'Database'],
    MediumDevelopmentFeature: ['Backend', 'Database'],
    LargeDevelopmentFeature: ['Backend', 'Database']
};
